controller_manager:
  ros__parameters:
    update_rate: 100 
  arm_controller:
    type: joint_trajectory_controller/JointTrajectoryController

  joint_state_broadcaster:
    type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    command_interfaces:
    - position
    state_interfaces:
    - position
    - velocity
    joints:
    - base_link
    - j1
    - j2
    - j3